version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: memedam-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  app:
    build: .
    container_name: memedam-backend
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://host.docker.internal:27017/memedam
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
